### ISSUE TITLE
Active fire confidence geotiff images do not have transparent background

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#545] opened 2022-10-18 16:03 UTC
Working with the new P2G V3.0 13 October tarball, I am now able to create images from both the MOD and IMG resolution active fire NetCDF files, but the confidence products for both (pct and cat) do not have transparent backgrounds.  The MOD files has a reddish background, and the IMG files have a yellow background. When you overlay the products on another geotiff, like true color, it looks like the file below:

![Image](https://user-images.githubusercontent.com/1848019/196483243-50dfa8bc-16fe-47f7-af42-c502e65ae7bc.png)

An example log file and imagery can be found here:  `bumi:/data/users/kathys/test_data/fire/fire_image_v3rc1`

**Comment by kathys** [comment] 2022-10-18 18:16
I did try this, and the T4, T13 and Power products all have transparent backgrounds, but not the confidence products:



![Image](https://user-images.githubusercontent.com/1848019/196511915-049e8166-e96e-49e7-9046-4790b5d63478.png)

**Comment by djhoese** [comment] 2022-10-19 18:21
Do you have an example of what v2.3 produced with the older format of these files?

As far as I can tell this is "expected" based on how the code is written right now. But I think I can work around the issues...or at least some of them. The problem is that the colormap being applied to the confidence is an RGB colormap (no alpha/transparency). That by itself is not the only problem as the `power` product is using that same colormap. The other problem is that both of the confidence products are considered category/integer products (yes, even `pct` which is saved as an integer field in the file with no scaling factor). The `_cat` product has a fill value of 0, the `_pct` product has a fill value of 255 (forced by Satpy to make it more consistent).

One of the bugs seems to be that the fill value information seems to be getting lost along the way. In the `power` case this isn't a problem since we assume NaN is the fill (floating point dataset), but for the integer variables we don't make any assumptions and simply assume all values are valid. This will be my first test, see if forcing the fill value will fix the output.

There is also a small chance that I'll be able to easily fix it for the case where `--fill-value` isn't specified on the command line but not when it is specified.

**Comment by kathys** [comment] 2022-10-19 18:42
For the same image as shown just above, it looks like this:

![Screen Shot 2022-10-19 at 1 41 27 PM](https://user-images.githubusercontent.com/1848019/196777047-5e7ca467-211e-4f0c-9c85-6d4248c8b4b2.png)

**Comment by kathys** [comment] 2022-10-19 18:43
If you are looking for this image, it is here, along with the log file:

`bumi:/data/users/kathys/test_data/fire/2022_fire_image`

**Comment by djhoese** [comment] 2022-10-23 18:47
The above trollimage PR has been merged and released. I just need to make a PR to tell the tarball creation to use the new version and then this should be close-able.

**Comment by djhoese** [comment] 2022-10-25 18:20
This should be available in the next tarball now that #549 is merged.

**Closed by djhoese** 2022-10-25 18:20 UTC
Labels: bug
