### ISSUE TITLE
Polar2Grid V2.3 and V3.0 MODIS predefined grid coverage differences

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#425] opened 2022-03-03 18:20 UTC
Working on comparing the output of a set of high resolution GeoTIFF images for a set of grids created from Aqua and Terra MODIS data.  The first thing that I notice is that the grid coverage thresholds are different between P2G Version 2.3 and Version 3.0.  There are a total of 8 grids I am using.  For the Terra dataset, Polar2Grid Version 2.3 resulted in 7 output files, whereas Polar2Grid Version 3.0 created only 4.  

I can see from the log files that P2G V3.0 messages state that these missing grids had "0.000000% of the output grid covered", but that is not true.  

Log files can be found here.  If you need more info, please let me know.

bumi:/data/users/kathys/version_3_0_timing/cutouts/terra_v2_3_output_gtiff
bumi:/data/users/kathys/version_3_0_timing/cutouts/terra_v3_0_output_gtiff

**Comment by kathys** [comment] 2022-03-03 18:39
Comparing the differences in the output true and false color differences now.  There are noticeable enhancement differences between the enhancements between the images products created between P2G Version 2.3 and Version 3.0.  The resolution looks the same, which is very good, so the sharpening looks the same, but the enhancement is definitely different.  I will try and load examples here.

Left panel Version 2.3, Right panel 3.0.  300m grid.

![Screen Shot 2022-03-03 at 12 36 58 PM](https://user-images.githubusercontent.com/1848019/156630207-c393e012-8d18-409b-b755-3810c30644a4.png)

![Screen Shot 2022-03-03 at 12 39 15 PM](https://user-images.githubusercontent.com/1848019/156630653-b8317f10-06f7-49f2-b408-d4c21ce044e1.png)

**Comment by djhoese** [comment] 2022-04-10 19:41
As mentioned on slack, the enhancement differences are caused by incorrect coefficients in the CREFL algorithm. They should be fixed in satpy shortly.

**Comment by djhoese** [comment] 2022-09-22 19:17
During out meeting I think @kathys said she would re-test this. If you remember this being fixed @kathys then I am OK closing this.

**Comment by kathys** [comment] 2022-09-22 19:19
Yes, I will take care of this.

**Comment by kathys** [comment] 2022-09-24 23:15
Confirmed that the enhancement has been fixed. The improvement in the resolution with the use of the 500m files is also obvious now.  Great! I was not sure @djhoese if the first part of this issue, the grid coverage part is supposed to already have been fixed?

**Comment by djhoese** [comment] 2022-09-25 04:31
Yes, I think this issue was before the major rewrite of the boundary polygon stuff.

**Closed by djhoese** 2022-09-25 04:31 UTC
Labels: bug, component:composite, component:enhancement
