### ISSUE TITLE
Some data issues with SFR mirs

### ISSUE THREAD

**Issue by spruceboy** [ssec/polar2grid#151] opened 2018-09-27 23:17 UTC
We are noticing some issues with MIRS SFR data with n19 and metopb, and are wondering how the "extra" missing data values are handled. 

The metadata for those files says:

```
                :missing_value = -999 ;
                :notretrievedproduct_value = -888 ;
                :noretrieval_value = -99 ;
```
 Some Examples of what this looks like:
![sfr_amsu_180927_1100](https://user-images.githubusercontent.com/243433/46179428-9f031700-c267-11e8-8ded-f6a161c37947.png)
![sfr_amsu_180927_1241](https://user-images.githubusercontent.com/243433/46179429-9f031700-c267-11e8-9624-3a88b501c49d.png)

Looking at the raw netcdf files with gdal, it looks to me like the regions that have the bad values show up as nodata, making wonder if gdal is masking off the other two nodata values? 

This could be a mistake on our end though.

**Comment by djhoese** [comment] 2018-09-27 23:19
What a strange set of fill values. iirc the MIRS reader/frontend only looks at the `missing_value`. If those other values are the problems then we'll have to add some extra logic.

**Comment by spruceboy** [comment] 2018-09-27 23:28
The ATMS data looks much more like what we expect: 
![sfr_amsu_180927_1355](https://user-images.githubusercontent.com/243433/46179818-8e53a080-c269-11e8-9aed-e6800f82bac5.png)

We (obviously) could be doing something wrong.   The NWS appears to be a lot of interest in the SFR (and the precipitation ) MIRS products, so if this is something I am doing wrong, let me know.

**Comment by spruceboy** [comment] 2018-09-27 23:28
Thanks for the awesome tool, btw!

**Comment by djhoese** [comment] 2022-04-04 20:46
Hello, 3.5 years later!

I'm going over old P2G issues and came across this one, but have no memory of if it was resolved or not (possibly over email). @spruceboy Not sure if you still get github notifications, but here we go...

There have been a lot of MiRS processing updates (not P2G) since this original issue. The little bit that I can remember is that this is/was likely a bug in the MiRS processing software where it should have marked these as fills. Even the new satpy-based readers for MiRS files do not check these other fill values. If anyone (@spruceboy or @kathys) knows if these fill values:

a. Still exist in the MiRS files
b. Are causing odd images in AWIPS

please let me know. If we can't find a reproducing case with modern versions of MiRS then I think we can close this. @kathys do you generate MiRS SFR geotiffs in production? Have you ever seen something like this?

**Comment by spruceboy** [comment] 2022-04-14 04:46
I can check with Carl D and see if he is still seeing the odd SFR values.  I don't look at the data much, he originally noticed the issue.  Thanks again for the great tool!

**Comment by djhoese** [comment] 2022-04-14 11:51
Carl confirmed over email that this issue no longer exists. His guess was that we switched from the legacy AWIPS 1 format to the "SCMI" tiles and that fixed the issue.

**Closed by djhoese** 2022-04-14 11:51 UTC
Labels: bug, question
