### ISSUE TITLE
"Fog" product being produced during the day for MODIS 

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#421] opened 2022-03-01 20:53 UTC
The "fog" product, which is really only an image that is made from the difference between the 4 and 11 micron brightness temperatures at night, was created along with the other default products for a daytime MODIS dataset that I am using.  The end result is an output GeoTIFF that is all white.  

If you need example files, please let me know.

**Comment by djhoese** [comment] 2022-03-02 19:34
Were there any log messages (debug probably) about percentage of day or night?

**Comment by kathys** [comment] 2022-03-02 20:00
Version 3.0 log file shows 
[2022-03-01 20:18:44,616] : PID  27657 : DEBUG    : polar2grid.filters._base : filter_scene : Analyzing 'DataID(name='fog', resolution=1000)' for filtering...
[2022-03-01 20:18:44,616] : PID  27657 : DEBUG    : polar2grid.filters.resample_coverage : _filter_data_array : Resampling found 49.653413% coverage.

Version 2.3 log file shows:
[2021-11-15 21:01:44,519] : PID  16119 : INFO     : polar2grid.viirs.swath : create_scene : Creating secondary product 'ifog'
[2021-11-15 21:01:45,477] : PID  16119 : DEBUG    : numpy : write : Warning: invalid value encountered in greater_equal
[2021-11-15 21:01:45,648] : PID  16119 : INFO     : polar2grid.viirs.swath : create_ifog : Less than 10% of the data is at night, will not create 'ifog' product

**Comment by djhoese** [comment] 2022-03-02 21:31
Looking at your log it looks like some of the SwathDefinitions are resulting in bad polygon math producing 900+% intersections...which is impossible.

**Comment by djhoese** [comment] 2022-03-02 21:44
Last question, does this data go over the anti-meridian?

**Comment by kathys** [comment] 2022-03-02 23:06
No it doesn't.  The closest that it comes is about 120 E.  

![Screen Shot 2022-03-02 at 5 05 24 PM](https://user-images.githubusercontent.com/1848019/156464757-8a33574c-660c-458e-9d36-f84727353871.png)

**Comment by djhoese** [comment] 2022-03-03 01:36
Can you point me to the input files. This is going to be difficult to reproduce otherwise...probably.

**Comment by kathys** [comment] 2022-03-03 15:03
bumi:/data/users/kathys/version_3_0_timing/input_modis_china

**Comment by djhoese** [comment] 2022-03-11 12:43
This is caused by the composite code in Satpy (the part that makes the difference) not properly setting the `standard_name` to `temperature_difference` which is used to determine how things are filtered. This can be closed once https://github.com/pytroll/satpy/pull/2054 is merged.

**Comment by djhoese** [comment] 2022-03-11 14:40
The satpy PR is now merged so the fix for this will be part of the next tarball (as it pulls in the most recent Satpy `main` branch).

**Comment by kathys** [comment] 2022-10-27 20:55
I just tested this with the V3.0 Oct. 25 tarball, and it is still creating the fog products for an Aqua MODIS daytime dataset that I am using over the US. images and log file here:
:
`bumi:/data/users/kathys/test_data/modis/aqua_tc_v3`

**Comment by kathys** [comment] 2022-10-27 20:56
The log file has this line in it:  [2022-10-27 20:19:14,406] : PID   2617 : DEBUG    : polar2grid.filters.day_night : _filter_data_array : Sunlight is estimated to cover nan% of the scene.

**Closed** 2022-11-02 20:42 UTC
Labels: bug
